# Generated by Django 2.1b1 on 2018-12-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
