# Generated by Django 2.1b1 on 2019-01-01 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Edit Bio', max_length=410),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_joining',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
