# Generated by Django 2.1b1 on 2019-01-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20190103_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followed_by',
            new_name='follows',
        ),
    ]
