# Generated by Django 2.1b1 on 2019-01-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20190103_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Select Your Profile Image', upload_to=''),
        ),
    ]
