# Generated by Django 2.1b1 on 2019-01-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Select Your Profile Image', upload_to='profile_images'),
        ),
    ]
