# Generated by Django 2.1b1 on 2019-01-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20190104_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Select Your Profile Image', upload_to=''),
        ),
    ]
