# Generated by Django 2.1b1 on 2019-02-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20190130_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(to='signup.Profile'),
        ),
    ]
