# Generated by Django 2.1b1 on 2019-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('Security', 'dgf50'), ('Level', 40), ('Info', 30), ('Updates', 20)], max_length=50),
        ),
    ]
