# Generated by Django 2.1b1 on 2019-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_auto_20190208_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[(50, 'Security'), (40, 'Level'), (30, 'Info'), (20, 'Updates')], max_length=50),
        ),
    ]
