# Generated by Django 2.1b1 on 2019-02-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0005_notifications_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
