# Generated by Django 2.1b1 on 2019-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0006_notifications_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('50', 'Security'), ('40', 'Level'), ('30', 'Info'), ('20', 'Updates'), ('10', 'Other')], max_length=50),
        ),
    ]
