# Generated by Django 2.1b1 on 2019-03-03 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0022_auto_20190111_2128'),
        ('signup', '0012_auto_20190207_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_reason', models.CharField(choices=[('1', 'Adult Content'), ('2', 'Misleading Advetisement'), ('3', 'Abusives Content'), ('4', 'Duplicate Thought'), ('5', 'Other')], max_length=100)),
                ('other_reason', models.CharField(blank=True, max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Profile')),
            ],
        ),
    ]
