# Generated by Django 2.1b1 on 2018-12-20 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(help_text='Write Your thought here...', max_length=15000)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, help_text='Use Image for Impowring your Thought', upload_to='')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('trending_ratio', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
