# Generated by Django 2.1b1 on 2018-12-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_profile_level'),
        ('home', '0005_down_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_profile',
            field=models.ForeignKey(default=-1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='signup.Profile'),
            preserve_default=False,
        ),
    ]
