# Generated by Django 2.1b1 on 2018-12-23 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20181222_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='down_vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='down_vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Down_vote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
