# Generated by Django 2.1b1 on 2018-12-28 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20181225_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dis_like',
            field=models.ManyToManyField(blank=True, related_name='dis_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
