# Generated by Django 2.1b1 on 2018-12-29 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
