# Generated by Django 2.1b1 on 2018-12-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_comment_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
