# Generated by Django 2.1b1 on 2019-01-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181230_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.CharField(default='tag', max_length=250),
            preserve_default=False,
        ),
    ]
