# Generated by Django 2.1b1 on 2019-01-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_posts_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='types',
            field=models.CharField(choices=[(1, 'Question'), (2, 'Creative Idea'), (3, 'Innovation'), (4, 'Nightmare'), (5, 'Thought')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
