# Generated by Django 2.1b1 on 2019-01-11 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0019_posts_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='views',
        ),
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
